Repository GDSC-SWU/2023-android-study, pull requests merged in 2023-09, with the labels that each got.

#12 Chaeyoung week1
  .idea/gradle.xml
  .idea/misc.xml
  Starbucks.zip
  app/src/main/res/drawable/center.xml
  app/src/main/res/drawable/grande.jpg
  app/src/main/res/drawable/heart_mark.jpg
  app/src/main/res/drawable/mjc.xml
  app/src/main/res/drawable/personal_option.jpg
  app/src/main/res/drawable/price.jpg
  app/src/main/res/drawable/right.xml
  app/src/main/res/drawable/round_btn.xml
  app/src/main/res/drawable/tall.jpg
  app/src/main/res/drawable/venti.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 🍇 채영(멤버), 💄 [UI]

#11 hayeon kim week1
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/baseline_add_circle_outline_24.xml
  app/src/main/res/drawable/baseline_arrow_back_ios_24.xml
  app/src/main/res/drawable/baseline_arrow_forward_ios_24.xml
  app/src/main/res/drawable/baseline_favorite_border_24.xml
  app/src/main/res/drawable/baseline_fit_screen_24.xml
  app/src/main/res/drawable/baseline_ios_share_24.xml
  app/src/main/res/drawable/baseline_remove_circle_outline_24.xml
  app/src/main/res/drawable/cake.jpg
  app/src/main/res/layout/activity_main.xml
Labels: 🍏 하연(멤버), 💄 [UI]

#10 soyeong week1
  .idea/gradle.xml
  .idea/misc.xml
  .idea/render.experimental.xml
  app/src/main/res/drawable/add_circle.xml
  app/src/main/res/drawable/arrow_back.xml
  app/src/main/res/drawable/arrow_forward.xml
  app/src/main/res/drawable/background.xml
  app/src/main/res/drawable/favorite.xml
  app/src/main/res/drawable/fit_screen.xml
  app/src/main/res/drawable/remove_circle.xml
  app/src/main/res/drawable/share.xml
  app/src/main/res/drawable/starbucks.jpg
  app/src/main/res/layout/activity_main.xml
Labels: 🍊 소영(멤버), 💄 [UI]

#9 [WEEK1] : startbucks view 구성
  app/build.gradle
  app/build.gradle.kts
  app/src/androidTest/java/com/example/starbucks/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starbucks/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/main_itemheart.xml
  app/src/main/res/drawable/main_itemimg.png
  app/src/main/res/drawable/main_itemminus.xml
  app/src/main/res/drawable/main_itemplus.xml
  app/src/main/res/drawable/main_plus.xml
  app/src/main/res/drawable/shadow_item_top.xml
  app/src/main/res/drawable/shape_green_fill_20.xml
  app/src/main/res/drawable/shape_green_line_20.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/starbucks/ExampleUnitTest.kt
Labels: 🐕 예림(코어), 💄 [UI]

#6 [WEEK1] : startbucks view 구성
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_green_btn.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/ic_white_btn.xml
  app/src/main/res/drawable/img_cake.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  img/ic_arrow.svg
  img/ic_back.svg
  img/ic_heart.svg
  img/ic_minus.svg
  img/ic_plus.svg
  img/ic_share.svg
Labels: 🍎 유진(멤버), 💄 [UI]

#5 [WEEK1] : startbucks view 구성
  app/src/main/java/com/example/gdsc/MainActivity.kt
  app/src/main/res/drawable/ic_add_circle.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_navigate_next.xml
  app/src/main/res/drawable/ic_remove_circle.xml
  app/src/main/res/drawable/img_cake.jpg
  app/src/main/res/drawable/shape_green_fill_20_rect.xml
  app/src/main/res/drawable/shape_green_line_20_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_starbucks_cake.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐈‍⬛ 소현(코어), 💄 [UI]

#13 Soyeong week2
  app/src/main/java/com/example/gdsc/Adapter.kt
  app/src/main/java/com/example/gdsc/Data.kt
  app/src/main/java/com/example/gdsc/MainActivity.kt
  app/src/main/res/drawable/add_circle.xml
  app/src/main/res/drawable/arrow_back.xml
  app/src/main/res/drawable/arrow_forward.xml
  app/src/main/res/drawable/coffee1.jpg
  app/src/main/res/drawable/coffee2.jpg
  app/src/main/res/drawable/coffee3.jpg
  app/src/main/res/drawable/coffee4.jpg
  app/src/main/res/drawable/coffee5.jpg
  app/src/main/res/drawable/favorite.xml
  app/src/main/res/drawable/fit_screen.xml
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/remove_circle.xml
  app/src/main/res/drawable/round_background.xml
  app/src/main/res/drawable/share.xml
  app/src/main/res/drawable/starbucks.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/recycler_item.xml
Labels: 🍊 소영(멤버)

#14 Hayeon kim week2
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/Adapter.kt
  app/src/main/java/com/example/gdsc/MusicActivity.kt
  app/src/main/java/com/example/gdsc/member.kt
  app/src/main/res/drawable/baseline_more_vert_24.xml
  app/src/main/res/drawable/img1.jpg
  app/src/main/res/drawable/img2.jpg
  app/src/main/res/drawable/img3.jpg
  app/src/main/res/drawable/img4.jpg
  app/src/main/res/drawable/img5.jpg
  app/src/main/res/drawable/img6.jpg
  app/src/main/res/drawable/img_style.xml
  app/src/main/res/layout/activity_recyclerview.xml
  app/src/main/res/layout/item.xml
Labels: 🍏 하연(멤버)

#15 2주차 과제 RecylerView 실습
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/Menu.kt
  app/src/main/java/com/example/gdsc/MenuActivity.kt
  app/src/main/java/com/example/gdsc/MenuAdapter.kt
  app/src/main/res/drawable/baseline_10k_24.xml
  app/src/main/res/drawable/baseline_10mp_24.xml
  app/src/main/res/drawable/baseline_11mp_24.xml
  app/src/main/res/drawable/baseline_12mp_24.xml
  app/src/main/res/drawable/baseline_22mp_24.xml
  app/src/main/res/drawable/baseline_more_vert_24.xml
  app/src/main/res/layout/activity_menu.xml
  app/src/main/res/layout/item_menu.xml
Labels: 🍋 소현(멤버)

#16 Chaeyoung week2
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/TalkActivity.kt
  app/src/main/java/com/example/gdsc/TalkAdapter.kt
  app/src/main/java/com/example/gdsc/Talker.kt
  app/src/main/res/drawable/apeach.png
  app/src/main/res/drawable/chaeyoung.png
  app/src/main/res/drawable/jenny.png
  app/src/main/res/drawable/lion.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/item.xml
  app/src/main/res/values/colors.xml
Labels: 🍇 채영(멤버)

#17 Youjin park week2
  .idea/aws.xml
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/Food.kt
  app/src/main/java/com/example/gdsc/FoodActivity.kt
  app/src/main/java/com/example/gdsc/FoodAdapter.kt
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/img_food_buger.jpg
  app/src/main/res/drawable/img_food_cake.jpg
  app/src/main/res/drawable/img_food_coffee.jpg
  app/src/main/res/drawable/img_food_pizza.jpg
  app/src/main/res/drawable/img_food_taco.jpg
  app/src/main/res/drawable/img_main_cake.png
  app/src/main/res/drawable/round_backgroud.xml
  app/src/main/res/layout/activity_food.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_food.xml
  app/src/main/res/values/strings.xml
  img/ic_menu.svg
Labels: 🍎 유진(멤버)

#19 [WEEK2] : 리사이클러뷰 실습
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/MainActivity.kt
  app/src/main/java/com/example/gdsc/ViewExt.kt
  app/src/main/java/com/example/gdsc/starbucksorder/StarbucksOrder.kt
  app/src/main/java/com/example/gdsc/starbucksorder/StarbucksOrderActivity.kt
  app/src/main/java/com/example/gdsc/starbucksorder/StarbucksOrderAdapter.kt
  app/src/main/java/com/example/gdsc/starbucksorder/StarbucksOrderViewModel.kt
  app/src/main/java/com/example/gdsc/starbucksorder/viewholder/StarbucksOrderViewHolder.kt
  app/src/main/res/font/font_pretendard_bold.xml
  app/src/main/res/font/font_pretendard_medium.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/layout/activity_starbucks_order.xml
  app/src/main/res/layout/item_starbucks_order.xml
  app/src/main/res/values/shapeAppearances.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐈‍⬛ 소현(코어), ✨ [FEAT], 💄 [UI]
