Repository GDSC-SWU/2023-android-study, pull requests merged in 2023-10, with the labels that each got.

#21 Sohyun park member week3
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/Menu.kt
  app/src/main/java/com/example/gdsc/MenuActivity.kt
  app/src/main/java/com/example/gdsc/MenuAdapter.kt
  app/src/main/java/com/example/gdsc/NaviActivity.kt
  app/src/main/java/com/example/gdsc/Page01Fragment.kt
  app/src/main/java/com/example/gdsc/Page02Fragment.kt
  app/src/main/java/com/example/gdsc/Page03Fragment.kt
  app/src/main/res/drawable/baseline_10k_24.xml
  app/src/main/res/drawable/baseline_10mp_24.xml
  app/src/main/res/drawable/baseline_11mp_24.xml
  app/src/main/res/drawable/baseline_12mp_24.xml
  app/src/main/res/drawable/baseline_22mp_24.xml
  app/src/main/res/drawable/baseline_more_vert_24.xml
  app/src/main/res/drawable/menu_click_color.xml
  app/src/main/res/layout/activity_menu.xml
  app/src/main/res/layout/activity_navi.xml
  app/src/main/res/layout/fragment_page01.xml
  app/src/main/res/layout/fragment_page02.xml
  app/src/main/res/layout/fragment_page03.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/menu/navi_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🍋 소현(멤버)

#25 안드로이드 3주차 과제 완성 (fragment)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/FirstFragment.kt
  app/src/main/java/com/example/gdsc/SecondFragment.kt
  app/src/main/java/com/example/gdsc/ThirdFragment.kt
  app/src/main/java/com/example/gdsc/Week3Activity.kt
  app/src/main/res/drawable/baseline_android_24.xml
  app/src/main/res/drawable/item_selector.xml
  app/src/main/res/layout/activity_week3.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/menu/item_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🍏 하연(멤버)

#26 soyeong week3
  app/src/main/java/com/example/gdsc/FirstFragment.kt
  app/src/main/java/com/example/gdsc/MainActivity.kt
  app/src/main/java/com/example/gdsc/SecondFragment.kt
  app/src/main/java/com/example/gdsc/ThirdFragment.kt
  app/src/main/res/drawable/ic_button.xml
  app/src/main/res/drawable/item_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/menu/item_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🍊 소영(멤버)

#27 week3 완성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/FirstFragment.kt
  app/src/main/java/com/example/gdsc/FragmentActivity.kt
  app/src/main/java/com/example/gdsc/SecondFragment.kt
  app/src/main/java/com/example/gdsc/ThirdFragment.kt
  app/src/main/res/drawable/ic_fragment.xml
  app/src/main/res/drawable/menu_click_color.xml
  app/src/main/res/layout/activity_fragment.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/menu/navi_bar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🍇 채영(멤버)

#28 youjin week3
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/Fragment1.kt
  app/src/main/java/com/example/gdsc/Fragment2.kt
  app/src/main/java/com/example/gdsc/Fragment3.kt
  app/src/main/java/com/example/gdsc/NavigationActivity.kt
  app/src/main/java/com/example/gdsc/UiActivity.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/activity_navigation.xml
  app/src/main/res/layout/activity_ui.xml
  app/src/main/res/layout/fragment_1.xml
  app/src/main/res/layout/fragment_2.xml
  app/src/main/res/layout/fragment_3.xml
  app/src/main/res/menu/item_menu.xml
  app/src/main/res/values/colors.xml
Labels: 🍎 유진(멤버)

#30 [WEEK3] : bottom navigation
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/bottomnavigation/FirstFragment.kt
  app/src/main/java/com/example/gdsc/bottomnavigation/MainActivity.kt
  app/src/main/java/com/example/gdsc/bottomnavigation/SecondFragment.kt
  app/src/main/java/com/example/gdsc/bottomnavigation/ThirdFragment.kt
  app/src/main/res/drawable/ic_android.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/menu/navigation_main.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: 🐈‍⬛ 소현(코어), ✨ [FEAT], 💄 [UI]

#32 [WEEK3] : bottom navigation
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/MainActivity.kt
  app/src/main/java/com/example/gdsc/week3/CalendarFragment.kt
  app/src/main/java/com/example/gdsc/week3/ChartFragment.kt
  app/src/main/java/com/example/gdsc/week3/CommentFragment.kt
  app/src/main/java/com/example/gdsc/week3/MainActivity.kt
  app/src/main/res/drawable/bottom_nevigation_selector.xml
  app/src/main/res/drawable/ic_bar_chart.xml
  app/src/main/res/drawable/ic_calendar_today.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_chart.xml
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/menu/bottom_nevigation_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐕 예림(코어), ✨ [FEAT], 💄 [UI]

#33 soyeong week4
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/Adapter.kt
  app/src/main/java/com/example/gdsc/ApiFactory.kt
  app/src/main/java/com/example/gdsc/MainActivity.kt
  app/src/main/java/com/example/gdsc/Member.kt
  app/src/main/java/com/example/gdsc/MemberApiService.kt
  app/src/main/res/drawable/img.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_introduction_gdsc_android.xml
  build.gradle.kts
Labels: 🍊 소영(멤버)

#34 3주차 서버 통신 실습
  app/.gitignore
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/ApiFactory.kt
  app/src/main/java/com/example/gdsc/IntroductionActivity.kt
  app/src/main/java/com/example/gdsc/IntroductionAdapter.kt
  app/src/main/java/com/example/gdsc/MemberApiService.kt
  app/src/main/java/com/example/gdsc/MemberDto.kt
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/item_member.xml
  build.gradle.kts
Labels: 🍋 소현(멤버)

#35 week4 완성
  Starbucks.zip
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/ApiFactory.kt
  app/src/main/java/com/example/gdsc/MemberApiService.kt
  app/src/main/java/com/example/gdsc/TalkActivity.kt
  app/src/main/java/com/example/gdsc/Talker.kt
  build.gradle.kts
Labels: 🍇 채영(멤버)

#36 youjin week4
  .gitignore
  .idea/misc.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/member/ApiFactory.kt
  app/src/main/java/com/example/gdsc/member/MemberActivity.kt
  app/src/main/java/com/example/gdsc/member/MemberAdapter.kt
  app/src/main/java/com/example/gdsc/member/MemberApiService.kt
  app/src/main/java/com/example/gdsc/member/MemberDto.kt
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/item_member.xml
  build.gradle.kts
Labels: 🍎 유진(멤버)

#38 [WEEK4] : api 연결
  app/.gitignore
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/data/ServicePool.kt
  app/src/main/java/com/example/gdsc/data/api/MemberApiService.kt
  app/src/main/java/com/example/gdsc/data/dto/MemberDto.kt
  app/src/main/java/com/example/gdsc/presentation/Introduction/IntroductionActivity.kt
  app/src/main/java/com/example/gdsc/presentation/Introduction/IntroductionAdapter.kt
  app/src/main/java/com/example/gdsc/presentation/starbucksorder/StarbucksOrder.kt
  app/src/main/java/com/example/gdsc/presentation/starbucksorder/StarbucksOrderActivity.kt
  app/src/main/java/com/example/gdsc/presentation/starbucksorder/StarbucksOrderAdapter.kt
  app/src/main/java/com/example/gdsc/presentation/starbucksorder/StarbucksOrderViewModel.kt
  app/src/main/java/com/example/gdsc/presentation/starbucksorder/viewholder/StarbucksOrderViewHolder.kt
  app/src/main/res/layout/activity_introduction_gdsc_android.xml
  app/src/main/res/layout/item_introduction_gdsc_android.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: 🐈‍⬛ 소현(코어), ✨ [FEAT]

#39 안드로이드 4주차 과제 완성 (서버 통신)
  app/.gitignore
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/ApiFactory.kt
  app/src/main/java/com/example/gdsc/IntroductionAdapter.kt
  app/src/main/java/com/example/gdsc/IntroductionViewHolder.kt
  app/src/main/java/com/example/gdsc/MemberApiService.kt
  app/src/main/java/com/example/gdsc/MemberDto.kt
  app/src/main/java/com/example/gdsc/Week4Activity.kt
  app/src/main/res/layout/activity_week4.xml
  app/src/main/res/layout/item_week4.xml
  build.gradle.kts
Labels: 🍏 하연(멤버)

#40 [WEEK4] : api 연결
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gdsc/week4/ApiFactory.kt
  app/src/main/java/com/example/gdsc/week4/MemberAdapter.kt
  app/src/main/java/com/example/gdsc/week4/MemberApiService.kt
  app/src/main/java/com/example/gdsc/week4/MemberListActivity.kt
  app/src/main/java/com/example/gdsc/week4/MemverDto.kt
  app/src/main/res/layout/activity_member_list.xml
  app/src/main/res/layout/member_item.xml
  build.gradle.kts
Labels: 🐕 예림(코어), ✨ [FEAT]
